title : Dev Docs
tagline: mmo development documents
author :
  name : Kevin Lynx
  email : kevinlynx@gmail.com
  github : kevinlynx
  twitter : kevinlynx
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
